name: Update auto streams

on:
  schedule:
    - cron: "* * * * *"   # हर 5 मिनट
  workflow_dispatch:        # Manual Run button

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch source JSONs
        run: |
          curl -fsSL https://allinonereborn.fun/fc/fancode.json -o fancode1.json || true
          curl -fsSL https://raw.githubusercontent.com/drmlive/fancode-live-events/main/fancode.json -o fancode2.json || true
          # Agar aur source ho to yahan add kar sakte ho

      - name: Run update script
        run: python ww_transform.py

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Auto update streams [Author Bot]" || echo "No changes to commit"
          git push
